# This is a basic workflow to help you get started with Actions

name: Deploy to server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Chane ssh keys to 600
        run: chmod 600 ${{secrets.KEY_SSH}}
        
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Installing composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
     
      - name: Installing dependencies
        run: php composer.phar update
        
      - name: Php init
        run: php init --env=Production --overwrite=All
        
      - name: Send directory to server
        uses: burnett01/rsync-deployments@4.1
        with:
            switches: -avzr --delete
            path: ./
            remote_path: /var/www/y
            remote_host: test-blade.ml
            remote_port: 37890
            remote_user: muser
            remote_key: ${{secrets.KEY}}
        
      - name: executing remote ssh commands using KEY
        uses: appleboy/ssh-action@master
        with:
          host: test-blade.ml
          username: muser
          port: 37890
          password: ${{secrets.PASSWORD}}
          script: cp /home/muser/configfiles/main-local.php /var/www/y/common/config/
